### ISSUE TITLE
Set up the Projects table and the ProjectsSkillsJunction table in the `employme-user` db

### ISSUE THREAD

**Issue by alexsieusahai** [alexsieusahai/employMe#16]
child of #12

**Comment by WeakMill98** [comment]
I dont get what ProjectSkills Junction is used for here.

**Comment by WeakMill98** [comment]
Nevermind, this looks fine.

**Comment by alexsieusahai** [comment]
For documentation purposes, the junction table is used since there is many skills corresponding to one project; it's a one to many relationship.
